name: Curious Poole
email: oflippence@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An illustration project by James Addison about the unseen curiosities of Poole
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: oflippence
github_username:  oflippence

markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
