# Site settings
title: Curious Poole
email: oflippence@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An illustration project by James Addison about the unseen curiosities of Poole
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  oflippence

# Build settings
markdown: kramdown
